### ISSUE TITLE
CRA: Extracting i18n plural keys produces error only for `jp` locales key

### ISSUE THREAD

**Issue by eckertalex** [gilbsgilbs/babel-plugin-i18next-extract#115]
**Describe the bug**

Create React App: Extracting i18n plural keys produces error only for `jp` locales key.

**How to reproduce**

- Clone [eckertalex/i18n-test](https://github.com/eckertalex/i18n-test)
- `npm install`
- `npm i18n-extract`

*Babel configuration:*

```
{
  "presets": ["react-app"],
  "plugins": [
    [
      "i18next-extract",
      {
        "locales": ["en", "jp"],
        "outputPath": "src/assets/locales/{{locale}}/{{ns}}.json",
        "defaultValue": "__NOT_YET_TRANSLATED__",
        "discardOldKeys": true
      }
    ]
  ]
}
```

*Reproduction:*

This `.babelrc` produces the error:
```
[ "i18next-extract",  { "locales": ["en", "jp"] } ]
```

This `.babelrc` does NOT produce the error:
```
[ "i18next-extract",  { "locales": ["en", "de"] } ]
```

**Expected behavior**

Extracting the plural keys should be independent of the locale strings provided in the `.babelrc`

**What actually happens**

![image](https://user-images.githubusercontent.com/19299600/71251723-6d221880-2323-11ea-8e6c-70e3e03d88d8.png)

**Your environment**

- OS: macOS Catalina (10.15.1)
- Plugin version: 0.4.2 
- Node version: 12.4.0

**Additional context**

Thanks for the help! Otherwise, I am enjoying this plugin!

![very-nice-thumbs-up-meme-1](https://user-images.githubusercontent.com/19299600/71251793-9773d600-2323-11ea-982e-dbf8f43d216b.jpg)

**Comment by gilbsgilbs** [comment]
Thanks for raising an issue. The locale name for the Japanese language is `ja` and not `jp` (see https://github.com/ladjs/i18n-locales). But the error message could definitely be improved :confused: .

**Comment by eckertalex** [comment]
Thanks for the quick response! Using `ja` instead of `jp` solved my issue.
An improved error message would definitely be appreciated :)
Thanks for the help!
