### ISSUE TITLE
Add customUseTranslationHooks configuration option

### ISSUE THREAD

**Issue by dprgarner** [gilbsgilbs/babel-plugin-i18next-extract#146]
**Is your feature request related to a problem? Please describe.**

I'm hoping to introduce this plugin on an app which has several internal library dependencies, each of which use i18next and react-i18next. To avoid potential clashes with these libraries and their i18next instances, I'd like to manually specify the instance of `i18n` to use within each call to the `useTranslations` hook. Rather than passing this in to the hook each time it's called, I'd prefer to create my own `useTranslations` hook in the app which does this, i.e.
```js
export const useTranslation = (ns, opts) => {
  return ReactI18Next.useTranslation(ns, { ...opts, i18n: i18nInstance });
};
```
However, this breaks namespace extraction, as this plugin is currently hard-coded to check that `useTranslation` is imported from `react-i18next`.

**Describe the solution you'd like**

I think the best solution would be to extend the configuration to support extraction on the user's custom `useTranslation` hooks. I believe this is in line with the current approach of the plugin: there's already a `customTransComponents` option that allows customisations like this for custom `<Trans>` components. The same API and most of the existing functions could be reused.

```jsx
/* Given the config options: */
{
  "customUseTranslationHooks": [
    ["./src/customComponents/i18n", "useMyTranslationHook"]
  ]
}

/* When run on the following code in `./src/MyCode.js`:  */
import {useMyTranslationHook} from "./customComponents/i18n";

function MyComponentWithNamespace() {
  const t = useMyTranslationHook('myNamespace');
  return <span>{t('extracted key in a namespace')}</span>
}

/* Then the output is: */
[{"extracted key in a namespace": ""}, {"ns": "myNamespace"}],
```

**Describe alternatives you've considered**

- *Just use `<Trans>` components in my app's code*. This would work, but the [react-i18next docs](https://react.i18next.com/latest/trans-component#important-note) recommend using `t()` instead of `<Trans>` when possible.
- *Don't use namespaces in my app's code*. I'd rather not lose these, though.
- *Fix the potential library clashes by somehow consolidating the i18next instances*. This seems much harder to get right, though; the libraries' translations and dependencies are easier to manage when they're independent.

**Additional context**

If you're happy with the suggested approach, I have the code ready to go for this.

**Comment by gilbsgilbs** [comment]
Hi,

Thanks for opening this feature request. I'm completely overwhelmed by a lot of things, so I'm not very active on the project right now, sorry.

My intuition is that your suggestion is completely acceptable as long as it matches the `customTransComponent` spec and implementation as closely as possible. I suggest that you make a PR should you have any code available, and I'll look into it as soon as I can find some air (which might not be soon depending on how complex the PR is).
