### ISSUE TITLE
ignore files inside node_modules

### ISSUE THREAD

**Issue by wuifdesign** [gilbsgilbs/babel-plugin-i18next-extract#196]
**Describe the bug**

Plugin should ignore files inside "node_modules", or at least have a setting for this.

**How to reproduce**

Import a package which uses `t` functions. ex: `@reduxjs/toolkit`, `react-i18next`

**Expected behavior**

Ignore files inside "node_modules"

**What actually happens**

Displays a warning:

```
babel-plugin-i18next-extract: Extraction error in /node_modules/@reduxjs/toolkit/node_modules/immer/dist/immer.esm.js at line 1. Couldn't evaluate i18next key. You should either make the key evaluable or skip the line using a skip comment (/* i18next-extract-disable-line */ or /* i18next-extract-disable-next-line */).
```

**Your environment**

- OS (e.g. ArchLinux): Mac
- Plugin version (e.g. 0.3.0): 0.8.3
- Node version (e.g. 12.13.0): 12

**Comment by kennethlynne** [comment]
We hit this today. Did you find a solution for this? 
It is an issue with libs like formik and dayjs too

**Comment by kennethlynne** [comment]
Our current workaround looks like this:

```
module.exports = function (api) {
  api.cache(true)

  return {
    plugins: [
      // workaround for https://github.com/gilbsgilbs/babel-plugin-i18next-extract/issues/196
      // to only enable it when we try to extract translations in a script and control the input, and not in the context of a bundler (metro etc)
      ...(process.env.EXTRACT_TRANSLATIONS === 'true'
        ? [
            [
              'i18next-extract',
              {
                locales: ['en', 'nb'],
                outputPath: 'src/translations/{{locale}}/translation.json',
                defaultValue: '',
                defaultContexts: [''],
                discardOldKeys: true,
              },
            ],
          ]
        : []),
    ],
  }
}
```

Then we're able to do stuff like this
```
 "translations:extract-keys": "cross-env EXTRACT_TRANSLATIONS=true yarn babel 'src/**/*.{js,jsx,ts,tsx}' --ignore '**/*.test.ts','**/*.test.tsx'",
```

**Comment by juliosampaio** [comment]
Same issue here :( Having a setting for this would be nice.

**Comment by hirbod** [comment]
@gilbsgilbs are you still maintaining this library? I get like thousands of error logs because it tries to search for a billion keys inside of node_modules

**Comment by gilbsgilbs** [comment]
@hirbod if you submit a PR, I'll gladly review, merge and publish a new release. I can't do it myself yet though, sorry.

**Comment by hirbod** [comment]
Alright, I'll try to see if I can exclude node_modules somehow. I just spent the whole day forking three different repos and I am investing more time fixing stuff than actually working currently :D
