### ISSUE TITLE
excludes doesn't seem to work

### ISSUE THREAD

**Issue by iDVB** [gilbsgilbs/babel-plugin-i18next-extract#230]
**Describe the bug**
Tried every number of glob patterns for `excludes` option and can't get anything to work. 
It always picks up on whatever is set in the CLI.

`yarn run babel --config-file ./babel-extract.config.js -o tmp/chunk.js 'src/**/*.{js,jsx,ts,tsx}' && rm -rf tmp`

**How to reproduce**

*Babel configuration:*

```
const { LOCALES, DEFAULT_LOCALE } = require('./languages')

process.env.NODE_ENV = 'test'

module.exports = {
  presets: ['babel-preset-gatsby'],
  plugins: [
    [
      'i18next-extract',
      {
        keySeparator: null,
        nsSeparator: null,
        locales: Object.keys(LOCALES),
        keyAsDefaultValue: [DEFAULT_LOCALE],
        useI18nextDefaultValue: [DEFAULT_LOCALE],
        discardOldKeys: true,
        defaultNS: 'common',
        outputPath: 'locales/{{locale}}/{{ns}}.json',
        customTransComponents: [['gatsby-plugin-react-i18next', 'Trans']],
        excludes: ['**/*'],
      },
    ],
  ],
}

```

**Expected behavior**
It should ignore processing on the files that follow given glob pattern.

**What actually happens**

all files specified in the CLI command are processed.

**Your environment**

- OS (e.g. ArchLinux): macOS v12.0.1
- Plugin version (e.g. 0.3.0): 0.8.3
- Node version (e.g. 12.13.0): v16.13.1

**Comment by gilbsgilbs** [comment]
Sorry, excludes are only available in [0.9.0-rc](https://github.com/gilbsgilbs/babel-plugin-i18next-extract/releases/tag/releases%2F0.9.0-rc) and [0.9.0-rc.1](https://github.com/gilbsgilbs/babel-plugin-i18next-extract/releases/tag/releases%2F0.9.0-rc.1). I need to make a final release.

Moreover, they are regexp. Not globs.
