### ISSUE TITLE
[BUG][0.9.1] Latest Release Packaging is broken?

### ISSUE THREAD

**Issue by yoroshikun** [gilbsgilbs/babel-plugin-i18next-extract#260]
**Describe the bug**

Thank you for your work on this library, however lately i have found that upgrading to the latest version seems to break the module?
It looks like the latest release was not built correctly? 0.9.1. as the package contains all the source code etc.

**How to reproduce**

Upgrade to 0.9.1

**Expected behavior**

No issues with file structure. Like so `0.9.0`
<img width="309" alt="image" src="https://github.com/gilbsgilbs/babel-plugin-i18next-extract/assets/1892447/78fea469-4447-4e90-8f0b-7b0cfba40b51">

**What actually happens**

File structure becomes this.
<img width="309" alt="image" src="https://github.com/gilbsgilbs/babel-plugin-i18next-extract/assets/1892447/b3e0d174-2c3e-4c8a-a6a3-76ff78eaf887">

**Additional context**

This i feel is urgent as it breaks all usage of the package. @gilbsgilbs 🙇

**Comment by gilbsgilbs** [comment]
Thanks for the report, that's my bad. Just published 0.9.2 to fix this, tell me if that works better.

**Comment by yoroshikun** [comment]
Works great, thank you!
