### ISSUE TITLE
Docs at netlify appears to be down/not running

### ISSUE THREAD

**Issue by frimmy** [gilbsgilbs/babel-plugin-i18next-extract#275]
**Describe the bug**

[Docs appear to be down](https://i18next-extract.netlify.com/)

**How to reproduce**
navigate to [https://i18next-extract.netlify.com/](https://i18next-extract.netlify.com/) 😅 

*Babel configuration:*
n/a
```
Paste your .babelrc here.
```

*Reproduction:*

```
Provide a code snippet that produce the unexpected result.
Try to isolate the bug and make this snippet as simple, concise and self-explanatory as possible.
```

**Expected behavior**
Expect to see docs site

**What actually happens**
Presented with Netlify's `Site Note Found` page:

![CleanShot 2024-05-23 at 08 07 25@2x](https://github.com/gilbsgilbs/babel-plugin-i18next-extract/assets/3891663/8aea9950-699c-4bed-92e2-aaa37f1bc91f)

**Your environment**

- OS (e.g. ArchLinux): MacOS
- Plugin version (e.g. 0.3.0): latest
- Node version (e.g. 12.13.0): n/a

**Additional context**

**Comment by gilbsgilbs** [comment]
Hi, thank you for the report. It seems that they finally dropped the redirection from `netlify.com` to `netlify.app` (see https://answers.netlify.com/t/deprecating-automatic-com-redirects/115442). As a result, docs is only accessible at the new URL: https://i18next-extract.netlify.app . I'll update the repo accordingly (which I should have done years ago, that's all on me 😝).
