### ISSUE TITLE
Only first t() key after a hook with specified namespace is put in that folder

### ISSUE THREAD

**Issue by CynthiaXJia** [gilbsgilbs/babel-plugin-i18next-extract#29]
I am using the plugin with settings:
useI18nextDefaultValue: true, keySeparator: null, discardOldKeys: true

I have a project where I'm using i18next with hooks and the t() function, and every component has its own namespace that is specified by const [t] = useTranslation('namespace').

However, only the first key used with t() in each component gets put in the proper namespace folder in extractedTranslations. The rest get shuffled into the default translation.json. Is this a bug or am I configuring something wrong?

Right now I'm just overriding with i18next-extract-mark-ns-start/stop comments to get everything in the folders I want.

**Comment by gilbsgilbs** [comment]
Thanks for raising an issue about this. This is definitely a bug. I think it's a regression I introduced in #15. I'll look into it and release a fix ASAP.

**Comment by gilbsgilbs** [comment]
@CynthiaXJia Should be fixed in 0.2.2 (release will come in the night :night_with_stars: )
