### ISSUE TITLE
Error in extracting when jsx contains spaces as {" "}

### ISSUE THREAD

**Issue by Pita** [gilbsgilbs/babel-plugin-i18next-extract#67]
We have this jsx:
```js
<Trans i18nKey="signup.tos">
  Mit der Registrierung des Nutzerkontos erkläre ich mich mit den{" "}
  <a
    href="https://www.polymore.com/tos"
    target="_blank"
    rel="noopener noreferrer"
  >
    AGB
  </a>{" "}
  einverstanden und bestätige die{" "}
  <a
    href="https://www.polymore.com/privacy"
    target="_blank"
    rel="noopener noreferrer"
  >
    Datenschutzerklärung
  </a>{" "}
  zur Kenntnis genommen zu haben.
</Trans>
```

Prettier automatically adds the spaces with {" "} to preserve them. The JSX above gets extracted as:

```js
    "tos": "Mit der Registrierung des Nutzerkontos erkläre ich mich mit den <3>AGB</3> einverstanden und bestätige die <8>Datenschutzerklärung</8> zur Kenntnis genommen zu haben.",
```

Notice how it counts 3 and 8 here. Now the final translation ends up as:

```
Mit der Registrierung des Nutzerkontos erkläre ich mich mit den einverstanden und bestätige die zur Kenntnis genommen zu haben. zur Kenntnis genommen zu haben.
```

Some values got lost and some get suddenly repeated. When I overwrite the counters to 2 & 6 as below, it all works as expected:
```
    "tos": "Mit der Registrierung des Nutzerkontos erkläre ich mich mit den <2>AGB</2> einverstanden und bestätige die <6>Datenschutzerklärung</6> zur Kenntnis genommen zu haben.",
```

So it seems like the counter gets confused by the spaces.

## Environment:
This is happening in a create react app, versions:
```
    "@babel/cli": "^7.6.0",
    "babel-plugin-i18next-extract": "^0.2.4",
    "react": "^16.8.6",
    "react-i18next": "^10.12.5",
```

**Comment by gilbsgilbs** [comment]
That's interesting. Thanks for the report. I wonder what happens:

- If you put `{" "}` in the middle of a line
- If you put `{"foo"}` at the one of a line

**Comment by Pita** [comment]
Maybe I can fix it real quick, pull request in progress

**Comment by gilbsgilbs** [comment]
Appreciated. :smile:

**Comment by Pita** [comment]
See https://github.com/gilbsgilbs/babel-plugin-i18next-extract/pull/68

**Comment by Pita** [comment]
@gilbsgilbs Are you gonna do a new release?

**Comment by gilbsgilbs** [comment]
@Pita should be good in 0.2.5. :tada:
