### ISSUE TITLE
How to remove unused keys from the JSON?

### ISSUE THREAD

**Issue by rpCal** [gilbsgilbs/babel-plugin-i18next-extract#8]
When I change code 
``` <Trans>Profile</Trans>```
to 
``` <Trans>Profil</Trans>```
I will receive two keys in translation.json
```
{
  "Profile": "",
  "Profil": ""
}
```

I want to have only fresh list of keys in translation file. 
Can you please tell is there any way to update config to handle that?

**Comment by gilbsgilbs** [comment]
Hi,

Thanks for raising an issue about this.

Initially, I did want to provide different merging strategies for the exporter and an option for this used to exist. Unfortunately, the plugin may get called multiple times by babel which makes it hard to know if it's safe to remove keys from the JSON or if they will be caught in an upcoming pass.

I'm unsure how to tackle this. I'd prefer to find a way to know if it's the last pass and the transpilation is going to end, but I didn't find a way to do this using the Babel plugin API. I'll have to think of it a bit more, unless somebody have a better idea.

**Comment by gilbsgilbs** [comment]
I edited the title, because I think it didn't relate what you really want. In your case, let's assume you had:

```json
{
  "MyKey": "Foo",
  "Profile": ""
}
```

What you really want as output is:

```json
{
  "MyKey": "Foo",
  "Profil": ""
}
```

keeping the value of `MyKey` if it was set. This is a bit different from recreating the translation files at each run.

Am I right?

**Comment by gilbsgilbs** [comment]
@rpCal, could you try to upgrade to `0.1.0-rc.1`, set the new `discardOldKeys` option to `true`  and tell me if it fits your needs?
