### ISSUE TITLE
Support `i18n.getFixedT(null, ns)` Namespace

### ISSUE THREAD

**Issue by hnryjms** [gilbsgilbs/babel-plugin-i18next-extract#96]
**Is your feature request related to a problem? Please describe.**

Using `react-i18n` hooks-style components, I've become used to the `useTranslation("namespace")` syntax where individual `t()` calls do not need a specific namespace specified since it can be inferred from the previous call.

When using a `redux-thunk` or `redux-saga` module, you aren't able to use the `useTranslation()` function since it does not run within a react context.

**Describe the solution you'd like**

There's a very similar function in i18n itself, [`i18next#getFixedT()`](https://www.i18next.com/overview/api#getfixedt) that returns a TFunction using a fixed namespace (or fixed language, of which doesn't apply here), that allows the `t()` behavior as found in `react-i18next`.

Right now, `babel-plugin-i18next-extract` does not know how to infer namespace from this wrapper function (it does extract `t()` calls from it, but in the wrong namespace). Presumably, the `extractors/useTranslationHook.ts` extractor could be cloned to support this `getFixedT()` function.

**Describe alternatives you've considered**

- `t("str", { ns: "namespace" })` a bunch of times. --> lots of repetitive namespace declarations :(

**Additional context**

See https://github.com/i18next/react-i18next/issues/845#issuecomment-488756883

**Comment by gilbsgilbs** [comment]
Thanks! If you feel like doing a PR, I think it could be very similar the [`useTranslation` hook](https://github.com/gilbsgilbs/babel-plugin-i18next-extract/blob/068bc34c163c0d0292074a8ccff38590451e692a/src/extractors/useTranslationHook.ts). However, note it won't work across files.

**Comment by hnryjms** [comment]
^ PR is opened :D

I'd think adding support would be step one ... building out fancier logic for tracking these calls across files isn't something my project does, but if some other fren comes across this discussion and knows a good way to implement that into this project, we'd surely appreciate it.

**Comment by gilbsgilbs** [comment]
> ^ PR #97 is opened :D

Wow, thanks :smile: .

> building out fancier logic for tracking these calls across files isn't something my project does, but if some other fren comes across this discussion and knows a good way to implement that into this project, we'd surely appreciate it.

I don't think it would be a good idea. It would add a lot of complexity and as Babel is just a parser, it doesn't suit cross-module logic anyways. I was just highlighting this in case you were expecting this to work anytime soon. I'm glad it's not the case :) .
